RI-503 gating: Run smoke and all tests in periodic jobs
* Set `TEMPEST_TESTS` based on periodic job.
  * deploy-smoke-tests => `--smoke`
  * deploy-full-tests => `--regex ^.*$`
* Reference failing Tempest tests in blacklist file.
* Expand and reformat tempestconf options.
  * `image.build_timeout 600`
  * `object-storage.operator_role Member`
* Catch Tempest exiting prematurely and incorrectly reporting success.
* Remove abandoned security groups after testing.
* Grab more logs from director as artifacts.
  * Instack undercloud installation log
  * Tempest log
* Rename log file artifacts to txt for viewing in web browser.

Issue: https://rpc-openstack.atlassian.net/browse/RI-503

diff --git a/gating/periodic/run b/gating/periodic/run
--- a/gating/periodic/run
+++ b/gating/periodic/run
@@ -24,3 +24,27 @@
 # RE_JOB_REPO_NAME: The project's GitHub repository which gets cloned in the
 # job. For example, for the repository found at
 # https://github.com/rcbops/rpc-gating, the name is rpc-gating.
+
+set -exu
+
+source "$(readlink -f $(dirname ${0}))/../env_vars"
+
+if [ "${OSP_JOB_ACTION}" = "deploy-smoke-tests" ]; then
+    export TEMPEST_TESTS='--smoke --blacklist-file /home/stack/tempest-blacklist.txt'
+elif [ "${OSP_JOB_ACTION}" = "deploy-full-tests" ]; then
+    # NOTE(coreywright): Explicitly specify the regex that matches all tests.
+    # Technically executing Tempest without specifying any tests causes it to
+    # run all tests, but between our use of an env var and Bash not always
+    # distinguishing between an env var that's unset and one that's set to
+    # null, explicitly specify all tests so the default test regex in build.sh
+    # doesn't get used.
+    export TEMPEST_TESTS='--regex ^.*$ --blacklist-file /home/stack/tempest-blacklist.txt'
+else
+    echo "ERROR: unhandled OSP_JOB_ACTION value: \"${OSP_JOB_ACTION}\""
+    exit 1
+fi
+
+# start the osp-mnaio build
+pushd /opt/osp-mnaio
+  ./build.sh
+popd
